### ISSUE TITLE
Type (instance) checking of `message` should allow for `ChatInputCommandInteraction`

### ISSUE THREAD

**Issue by AceLikesGhosts** [3061LRTAGSPKJMORMRT/discord-blackjack#11]
Type (instance) checking of `message` should allow for `ChatInputCommandInteraction` as well, due to it essentially being the same thing as a `CommandInteraction`.

**Comment by AceLikesGhosts** [comment]
https://github.com/3061LRTAGSPKJMORMRT/discord-blackjack/blob/78028ac472926fdb1253601c079045c092a80e2e/src/index.js#L41

**Comment by 3061LRTAGSPKJMORMRT** [comment]
I would do this, but some people who use message command still get errors that an invalid parameter was provided. I am not sure what's really causing this and I want to support both v13 and v14 packages using the same code.

**Comment by AceLikesGhosts** [comment]
Could you not check if `message` is an instance of [BaseInteraction](https://discord.js.org/#/docs/discord.js/main/class/BaseInteraction) as every Interaction extends from that?

**Comment by AceLikesGhosts** [comment]
`ChatInputCommandInteraction` AND `CommandInteraction` extend from `Interaction`. Using a bit of JS jank you could (theoretically) do something along the lines of `Object.prototype.isPrototypeOf.call(A.prototype, B.prototype)` where B is the class that extends from A. (IE: `Interaction` and `CommandInteraction`)

Purely hypothetical although I believe it should work. Going to test locally and let you know (:

**Comment by AceLikesGhosts** [comment]
that works for inheritance checks : I forgot for a month

**Comment by AceLikesGhosts** [comment]
Ended up making my own [fork](https://github.com/turel-bot/discord-blackjack) of this so I can get it to work w latest DJS (:

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Alright. I apologize as I couldn't assist you as it's been a while since I updated the library. I'll probably make a new update when djs v15 comes out
