### ISSUE TITLE
import 

### ISSUE THREAD

**Issue by NicolasBuscarini** [3061LRTAGSPKJMORMRT/discord-blackjack#8]
![image](https://user-images.githubusercontent.com/78824150/157231766-3238a59e-78b9-42ae-9db9-3c54661c4339.png)
I wanna Type blackjack. Can you help me ?

![image](https://user-images.githubusercontent.com/78824150/157231950-51dc6e69-ec84-478b-82f5-fff910b6e383.png)

**Comment by 3061LRTAGSPKJMORMRT** [comment]
I'm sorry, I didn't get you. What is your issue? 

Note that I'm not experienced with TypeScript so I may not understand you properly

**Comment by NicolasBuscarini** [comment]
I did a search and realized that there is no way to do it in javascript. thanks for the answer
