### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by NicolasBuscarini** [3061LRTAGSPKJMORMRT/discord-blackjack#9]
I would like to be able to change the properties of these buttons. Would you know how to do this?

![image](https://user-images.githubusercontent.com/78824150/157442889-79e1fc1b-05c5-41b3-9722-da2cc388d4a7.png)

code:
```
    let embed = {
        title: "Blackjack game",
        color: "RANDOM",
        fields: [
            {name: `Mão do ${userMember.nickname}`, value: '\u200B', inline : true },
            {name: `Mão do Dealer`, value: '\u200B', inline: true },
        ],
    }

    let game = await blackjack(interaction, {resultEmbed: false, normalEmbed: false, normalEmbedContent: embed} );
```

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Hi, no you can't change the labels unless you manually edit the file. However, in the next update, i will add an option to edit the labels.

**Comment by NicolasBuscarini** [comment]
Thank you
